# Generated by Django 5.2 on 2025-11-07 11:10

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_type', models.CharField(choices=[('ASSIGNMENT', 'Assignment'), ('QUIZ', 'Quiz'), ('EXAM', 'Exam')], default='QUIZ', max_length=20)),
                ('parent_id', models.PositiveIntegerField(help_text='ID of the parent Assignment/Quiz/Exam.')),
                ('question_type', models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('CODE', 'Coding Question'), ('TEXT', 'Text Answer Question')], default='MCQ', max_length=10)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='questions/')),
                ('marks', models.FloatField(default=1)),
                ('allow_custom_answer', models.BooleanField(default=False, help_text='If enabled, user can type their own answer.')),
                ('correct_answer_text', models.TextField(blank=True, help_text='For text/coding questions.', null=True)),
                ('correct_option', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option label for MCQ.', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_status', models.CharField(choices=[('ONLINE', 'Online'), ('OFFLINE', 'Offline')], default='ONLINE', max_length=20)),
                ('system_pin', models.CharField(default='4321', max_length=10)),
                ('system_root', models.CharField(default='admin', max_length=100)),
                ('pin_required', models.BooleanField(default=True, help_text='If disabled, PIN not required for login.')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_banned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, help_text='Last time the user was active.')),
                ('is_online', models.BooleanField(default=False, help_text='Whether the user is currently online or not.')),
            ],
        ),
        migrations.CreateModel(
            name='CalendarEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('description', models.TextField(blank=True, null=True)),
                ('event_type', models.CharField(choices=[('ASSIGNMENT_OPEN', 'Assignment Opened'), ('QUIZ_OPEN', 'Quiz Opened'), ('EXAM_OPEN', 'Exam Opened'), ('DEADLINE', 'Submission Deadline'), ('NOTICE', 'General Notice')], default='NOTICE', max_length=50)),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moodle.course')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Total duration in minutes.')),
                ('max_attempts', models.IntegerField(default=1, help_text='How many times a student can attempt.')),
                ('is_live', models.BooleanField(default=False, help_text='If enabled, this assessment becomes visible and attemptable by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Total duration in minutes.')),
                ('max_attempts', models.IntegerField(default=1, help_text='How many times a student can attempt.')),
                ('is_live', models.BooleanField(default=False, help_text='If enabled, this assessment becomes visible and attemptable by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.course')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_label', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('text', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='options/')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='moodle.question')),
            ],
            options={
                'ordering': ['option_label'],
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('open_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('close_date', models.DateTimeField(blank=True, null=True)),
                ('duration_minutes', models.IntegerField(default=60, help_text='Total duration in minutes.')),
                ('max_attempts', models.IntegerField(default=1, help_text='How many times a student can attempt.')),
                ('is_live', models.BooleanField(default=False, help_text='If enabled, this assessment becomes visible and attemptable by users.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='moodle.course')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
