# Generated by Django 5.2 on 2025-11-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, default='course_images/default.jpg', null=True, upload_to='course_images/'),
        ),
    ]
