# Generated by Django 5.2 on 2025-11-07 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0002_course_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='course_images/'),
        ),
    ]
