# Generated by Django 4.2.26 on 2025-11-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0003_alter_course_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='show_answer',
            field=models.BooleanField(default=True, help_text='If disabled, Options not shows in Tests'),
        ),
    ]
