# Generated by Django 4.2.26 on 2025-11-29 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0004_systemconfig_show_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemconfig',
            name='show_answer',
            field=models.BooleanField(default=True, help_text='If disabled, Answers not shows in Tests'),
        ),
    ]
