# Generated by Django 4.2.26 on 2025-11-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0005_alter_systemconfig_show_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='For MCQ: Correct option label. For True/False: A=True, B=False', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('TF', 'True / False'), ('CODE', 'Coding Question'), ('TEXT', 'Text Answer Question')], default='MCQ', max_length=10),
        ),
    ]
