# Generated by Django 4.2.26 on 2025-11-29 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0006_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_option',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], help_text='Correct option label for MCQ.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('MCQ', 'Multiple Choice Question'), ('CODE', 'Coding Question'), ('TEXT', 'Text Answer Question')], default='MCQ', max_length=10),
        ),
    ]
