# Generated by Django 4.2.26 on 2025-11-30 21:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('moodle', '0007_alter_question_correct_option_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertable',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usertable',
            name='last_active',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
